import * as React from "react";
import Head from "next/head";
import type { NextPage } from "next";

import NavBar from "../../components/NavBar";
import UsersDetail from "../../components/UsersDetail";

const Detail: NextPage = () => {
  return (
    <React.Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav>
        <NavBar />
      </nav>
      <main>
        <UsersDetail />
      </main>
      <footer>futer</footer>
    </React.Fragment>
  );
};

export default Detail;
